genai_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'genai') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'changeme') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'genai_db') }}"
      schema: public
      threads: 2
