services:
  airflow:
    image: apache/airflow:2.7.1
    restart: unless-stopped
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: "/opt/airflow/project"
      _PIP_ADDITIONAL_REQUIREMENTS: "psycopg2-binary sqlalchemy pandas"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./outputs:/opt/airflow/outputs
      - ./:/opt/airflow/project
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
              airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
              airflow webserver & sleep 5 && airflow scheduler"
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10

  chroma:
    image: chromadb/chroma:1.1.1
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_TELEMETRY=False
      - CHROMA_PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped



  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit/Dockerfile
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      CHROMA_HOST: "chroma"
      CHROMA_HTTP_PORT: "${CHROMA_HTTP_PORT:-8000}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - postgres
      - chroma

volumes:
  postgres_data:
  chroma_data:
