version: 2

sources:
  - name: raw
    description: "Raw tables loaded by ETL into Postgres public schema."
    schema: public
    tables:
      - name: raw_orders
        description: "Raw orders data"
      - name: raw_shipments
        description: "Raw shipments data"
      - name: raw_inventory
        description: "Raw inventory data"
